name: ali_pasha_graph
description: "Ali-pasha2 With GraphQl"
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  get: ^4.6.6
  dio: ^5.7.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  flutter_svg_provider: ^1.0.7
  path_provider: ^2.1.4
  flutter_screenutil: ^5.9.3

#  readmore: ^3.0.0
  get_storage: ^2.1.1
  dio_cache_interceptor: ^3.5.0
  image_picker: ^1.1.2
  image_cropper: ^8.0.2

  select2dot1: ^2.0.9
  location: ^5.0.3
  badges: ^3.1.2
  dropdown_button2: ^2.3.9
  logger: ^2.4.0

  intl: ^0.19.0
  cherry_toast: ^1.11.0
  change_app_package_name: ^1.3.0
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.2
  firebase_analytics: ^11.3.2
  toast: ^0.3.0
  url_launcher: ^6.3.0
  animated_custom_dropdown: ^3.1.1
#  laravel_flutter_pusher_plus:
#    git:
#      url: https://github.com/MohanadAlShamey/ali-pash-pusher-lib.git
#      ref: main
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.3.0
  flutter_widget_from_html_core: ^0.15.2
  flutter_form_builder: ^9.4.1
  form_builder_validators: ^11.0.0

  form_builder_image_picker: ^4.1.0
  form_builder_file_picker: ^4.2.0
  form_builder_extra_fields: ^11.0.0
  share_plus: ^10.0.2
  permission_handler: ^11.3.1
  pusher_client_socket: ^0.0.1
  app_links: ^6.3.2
  shimmer: ^3.0.0
  another_audio_recorder: ^1.2.1
  audioplayers: ^6.1.0
#  flutter_sound: ^9.6.0
#  audio_session: ^0.1.20






dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/svg/
    - assets/images/png/
  #   - images/a_dot_ham.jpeg


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

